=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

$fibonacci = [1,2]
sum = 2

def newTerm
  var = $fibonacci[$fibonacci.length - 1] + $fibonacci[$fibonacci.length - 2]
end

while (newTerm <= 4 * 10**6)
  $fibonacci.push newTerm
  if (newTerm % 2 == 0)
    sum = sum + newTerm
  end
end

puts sum
